/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_inscription (void)
{
  GtkWidget *inscription;
  GtkWidget *fixed27;
  GtkWidget *entry_nom_ins;
  GtkWidget *entry_prenom_ins;
  GtkWidget *entry_login_ins;
  GtkWidget *entry_mdp_ins;
  GtkWidget *prenom;
  GtkWidget *nom;
  GtkWidget *mot_de_pase;
  GtkWidget *login;
  GtkWidget *inscrire;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label101;

  inscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (inscription), _("Inscription"));
  gtk_window_set_position (GTK_WINDOW (inscription), GTK_WIN_POS_CENTER);
  gtk_window_set_gravity (GTK_WINDOW (inscription), GDK_GRAVITY_CENTER);

  fixed27 = gtk_fixed_new ();
  gtk_widget_show (fixed27);
  gtk_container_add (GTK_CONTAINER (inscription), fixed27);

  entry_nom_ins = gtk_entry_new ();
  gtk_widget_show (entry_nom_ins);
  gtk_fixed_put (GTK_FIXED (fixed27), entry_nom_ins, 128, 8);
  gtk_widget_set_size_request (entry_nom_ins, 144, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_ins), 8226);

  entry_prenom_ins = gtk_entry_new ();
  gtk_widget_show (entry_prenom_ins);
  gtk_fixed_put (GTK_FIXED (fixed27), entry_prenom_ins, 128, 56);
  gtk_widget_set_size_request (entry_prenom_ins, 144, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_ins), 8226);

  entry_login_ins = gtk_entry_new ();
  gtk_widget_show (entry_login_ins);
  gtk_fixed_put (GTK_FIXED (fixed27), entry_login_ins, 128, 112);
  gtk_widget_set_size_request (entry_login_ins, 144, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login_ins), 8226);

  entry_mdp_ins = gtk_entry_new ();
  gtk_widget_show (entry_mdp_ins);
  gtk_fixed_put (GTK_FIXED (fixed27), entry_mdp_ins, 128, 168);
  gtk_widget_set_size_request (entry_mdp_ins, 144, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mdp_ins), 8226);

  prenom = gtk_label_new (_("Prenom"));
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed27), prenom, 0, 56);
  gtk_widget_set_size_request (prenom, 72, 32);

  nom = gtk_label_new (_("Nom"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed27), nom, 8, 16);
  gtk_widget_set_size_request (nom, 56, 24);

  mot_de_pase = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (mot_de_pase);
  gtk_fixed_put (GTK_FIXED (fixed27), mot_de_pase, 0, 176);
  gtk_widget_set_size_request (mot_de_pase, 104, 32);

  login = gtk_label_new (_("Login"));
  gtk_widget_show (login);
  gtk_fixed_put (GTK_FIXED (fixed27), login, 0, 120);
  gtk_widget_set_size_request (login, 64, 23);

  inscrire = gtk_button_new ();
  gtk_widget_show (inscrire);
  gtk_fixed_put (GTK_FIXED (fixed27), inscrire, 320, 88);
  gtk_widget_set_size_request (inscrire, 120, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (inscrire), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox14), label101, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) inscrire, "clicked",
                    G_CALLBACK (on_inscrire_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscription, inscription, "inscription");
  GLADE_HOOKUP_OBJECT (inscription, fixed27, "fixed27");
  GLADE_HOOKUP_OBJECT (inscription, entry_nom_ins, "entry_nom_ins");
  GLADE_HOOKUP_OBJECT (inscription, entry_prenom_ins, "entry_prenom_ins");
  GLADE_HOOKUP_OBJECT (inscription, entry_login_ins, "entry_login_ins");
  GLADE_HOOKUP_OBJECT (inscription, entry_mdp_ins, "entry_mdp_ins");
  GLADE_HOOKUP_OBJECT (inscription, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (inscription, nom, "nom");
  GLADE_HOOKUP_OBJECT (inscription, mot_de_pase, "mot_de_pase");
  GLADE_HOOKUP_OBJECT (inscription, login, "login");
  GLADE_HOOKUP_OBJECT (inscription, inscrire, "inscrire");
  GLADE_HOOKUP_OBJECT (inscription, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (inscription, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (inscription, image14, "image14");
  GLADE_HOOKUP_OBJECT (inscription, label101, "label101");

  return inscription;
}

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed1;
  GtkWidget *entrylogin;
  GtkWidget *entrymdp;
  GtkWidget *image36;
  GtkWidget *mot_de_passe;
  GtkWidget *login;
  GtkWidget *connecter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *label5;
  GtkWidget *image2;
  GtkWidget *retoursauthentifier;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *label4;
  GtkWidget *image1;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (authentification), _("se connecter"));
  gtk_window_set_position (GTK_WINDOW (authentification), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (authentification), fixed1);

  entrylogin = gtk_entry_new ();
  gtk_widget_show (entrylogin);
  gtk_fixed_put (GTK_FIXED (fixed1), entrylogin, 312, 256);
  gtk_widget_set_size_request (entrylogin, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrylogin), 8226);

  entrymdp = gtk_entry_new ();
  gtk_widget_show (entrymdp);
  gtk_fixed_put (GTK_FIXED (fixed1), entrymdp, 312, 296);
  gtk_widget_set_size_request (entrymdp, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdp), 8226);

  image36 = create_pixmap (authentification, "farm-background-2560x1600-htc-WTG3047373-1024x640.jpeg");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed1), image36, 0, 0);
  gtk_widget_set_size_request (image36, 1024, 640);

  mot_de_passe = gtk_label_new (_("<span color=\"teal\">Mot de passe</span>"));
  gtk_widget_show (mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed1), mot_de_passe, 192, 304);
  gtk_widget_set_size_request (mot_de_passe, 113, 16);
  gtk_label_set_use_markup (GTK_LABEL (mot_de_passe), TRUE);

  login = gtk_label_new (_("<span color =\"teal\">Login</span>"));
  gtk_widget_show (login);
  gtk_fixed_put (GTK_FIXED (fixed1), login, 200, 256);
  gtk_widget_set_size_request (login, 57, 25);
  gtk_label_set_use_markup (GTK_LABEL (login), TRUE);

  connecter = gtk_button_new ();
  gtk_widget_show (connecter);
  gtk_fixed_put (GTK_FIXED (fixed1), connecter, 520, 424);
  gtk_widget_set_size_request (connecter, 128, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (connecter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  label5 = gtk_label_new_with_mnemonic (_("<span color =\"teal\">Se connecter</span>"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 3);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  retoursauthentifier = gtk_button_new ();
  gtk_widget_show (retoursauthentifier);
  gtk_fixed_put (GTK_FIXED (fixed1), retoursauthentifier, 384, 424);
  gtk_widget_set_size_request (retoursauthentifier, 113, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (retoursauthentifier), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  label4 = gtk_label_new_with_mnemonic (_("<span color =\"teal\">Retour</span>"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 10);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  image1 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) connecter, "clicked",
                    G_CALLBACK (on_connecter_clicked),
                    NULL);
  g_signal_connect ((gpointer) retoursauthentifier, "clicked",
                    G_CALLBACK (on_retoursauthentifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (authentification, entrylogin, "entrylogin");
  GLADE_HOOKUP_OBJECT (authentification, entrymdp, "entrymdp");
  GLADE_HOOKUP_OBJECT (authentification, image36, "image36");
  GLADE_HOOKUP_OBJECT (authentification, mot_de_passe, "mot_de_passe");
  GLADE_HOOKUP_OBJECT (authentification, login, "login");
  GLADE_HOOKUP_OBJECT (authentification, connecter, "connecter");
  GLADE_HOOKUP_OBJECT (authentification, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (authentification, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (authentification, label5, "label5");
  GLADE_HOOKUP_OBJECT (authentification, image2, "image2");
  GLADE_HOOKUP_OBJECT (authentification, retoursauthentifier, "retoursauthentifier");
  GLADE_HOOKUP_OBJECT (authentification, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (authentification, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (authentification, label4, "label4");
  GLADE_HOOKUP_OBJECT (authentification, image1, "image1");

  return authentification;
}

GtkWidget*
create_gestion_capteur (void)
{
  GtkWidget *gestion_capteur;
  GtkWidget *fixed4;
  GtkWidget *entry4;
  GtkWidget *combobox9;
  GtkWidget *refrech;
  GtkWidget *image24;
  GtkWidget *modifierg;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *label47;
  GtkWidget *image4;
  GtkWidget *supprimerg;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *label48;
  GtkWidget *image5;
  GtkWidget *alarmants;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *label132;
  GtkWidget *image26;
  GtkWidget *ajouter;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *label146;
  GtkWidget *image32;
  GtkWidget *retourg;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *label49;
  GtkWidget *image6;
  GtkWidget *butt_cherch_gest;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label109;
  GtkWidget *chercher_diff;
  GtkWidget *image27;
  GtkWidget *def_marque;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *label154;
  GtkWidget *image45;
  GtkWidget *label131;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *ajout_val;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *label156;
  GtkWidget *image25;
  GtkWidget *labeldef;

  gestion_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_capteur), _("Gestion Capteur"));
  gtk_window_set_position (GTK_WINDOW (gestion_capteur), GTK_WIN_POS_CENTER);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (gestion_capteur), fixed4);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed4), entry4, 0, 8);
  gtk_widget_set_size_request (entry4, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  combobox9 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox9);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox9, 0, 56);
  gtk_widget_set_size_request (combobox9, 144, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("PANNE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("OK"));

  refrech = gtk_button_new ();
  gtk_widget_show (refrech);
  gtk_fixed_put (GTK_FIXED (fixed4), refrech, 272, 0);
  gtk_widget_set_size_request (refrech, 30, 30);

  image24 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_container_add (GTK_CONTAINER (refrech), image24);

  modifierg = gtk_button_new ();
  gtk_widget_show (modifierg);
  gtk_fixed_put (GTK_FIXED (fixed4), modifierg, 0, 176);
  gtk_widget_set_size_request (modifierg, 144, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (modifierg), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  label47 = gtk_label_new_with_mnemonic (_("<span color =\"Teal\">Modifier</span>"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox4), label47, FALSE, FALSE, 27);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  supprimerg = gtk_button_new ();
  gtk_widget_show (supprimerg);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimerg, 0, 256);
  gtk_widget_set_size_request (supprimerg, 144, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (supprimerg), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  label48 = gtk_label_new_with_mnemonic (_("<span color =\"Teal\">Supprimer</span>"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox5), label48, FALSE, FALSE, 21);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  alarmants = gtk_button_new ();
  gtk_widget_show (alarmants);
  gtk_fixed_put (GTK_FIXED (fixed4), alarmants, 0, 296);
  gtk_widget_set_size_request (alarmants, 144, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (alarmants), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  label132 = gtk_label_new_with_mnemonic (_("  <span color=\"Teal\">Historique</span>"));
  gtk_widget_show (label132);
  gtk_box_pack_start (GTK_BOX (hbox20), label132, FALSE, FALSE, 17);
  gtk_label_set_use_markup (GTK_LABEL (label132), TRUE);

  image26 = gtk_image_new_from_stock ("gtk-cdrom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox20), image26, FALSE, FALSE, 0);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), ajouter, 0, 136);
  gtk_widget_set_size_request (ajouter, 144, 32);
  gtk_button_set_focus_on_click (GTK_BUTTON (ajouter), FALSE);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  label146 = gtk_label_new (_("  <span color=\"Teal\">Ajouter</span>"));
  gtk_widget_show (label146);
  gtk_box_pack_start (GTK_BOX (hbox25), label146, FALSE, FALSE, 28);
  gtk_label_set_use_markup (GTK_LABEL (label146), TRUE);

  image32 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox25), image32, FALSE, FALSE, 0);

  retourg = gtk_button_new ();
  gtk_widget_show (retourg);
  gtk_fixed_put (GTK_FIXED (fixed4), retourg, 872, 600);
  gtk_widget_set_size_request (retourg, 144, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (retourg), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  label49 = gtk_label_new_with_mnemonic (_("<span color =\"teal\">Deconnecter</span>"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox6), label49, FALSE, FALSE, 15);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  butt_cherch_gest = gtk_button_new ();
  gtk_widget_show (butt_cherch_gest);
  gtk_fixed_put (GTK_FIXED (fixed4), butt_cherch_gest, 144, 8);
  gtk_widget_set_size_request (butt_cherch_gest, 30, 30);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (butt_cherch_gest), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label109 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox15), label109, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label109), TRUE);

  chercher_diff = gtk_button_new ();
  gtk_widget_show (chercher_diff);
  gtk_fixed_put (GTK_FIXED (fixed4), chercher_diff, 144, 56);
  gtk_widget_set_size_request (chercher_diff, 30, 30);

  image27 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_container_add (GTK_CONTAINER (chercher_diff), image27);

  def_marque = gtk_button_new ();
  gtk_widget_show (def_marque);
  gtk_fixed_put (GTK_FIXED (fixed4), def_marque, 0, 472);
  gtk_widget_set_size_request (def_marque, 128, 40);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (def_marque), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  label154 = gtk_label_new_with_mnemonic (_("Marque"));
  gtk_widget_show (label154);
  gtk_box_pack_start (GTK_BOX (hbox30), label154, FALSE, FALSE, 12);

  image45 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox30), image45, FALSE, FALSE, 0);

  label131 = gtk_label_new_with_mnemonic (_("  <span color=\"Teal\">Valeur</span>"));
  gtk_widget_show (label131);
  gtk_fixed_put (GTK_FIXED (fixed4), label131, 0, 0);
  gtk_widget_set_size_request (label131, 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label131), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 320, 0);
  gtk_widget_set_size_request (scrolledwindow1, 696, 560);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport1), GTK_SHADOW_NONE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 0, 0);
  gtk_widget_set_size_request (treeview1, 688, 1528);
  gtk_container_set_border_width (GTK_CONTAINER (treeview1), 5);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview1), TRUE);
  gtk_tree_view_set_hover_selection (GTK_TREE_VIEW (treeview1), TRUE);

  ajout_val = gtk_button_new ();
  gtk_widget_show (ajout_val);
  gtk_fixed_put (GTK_FIXED (fixed4), ajout_val, 0, 216);
  gtk_widget_set_size_request (ajout_val, 144, 32);
  gtk_button_set_focus_on_click (GTK_BUTTON (ajout_val), FALSE);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (ajout_val), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  label156 = gtk_label_new (_("  <span color=\"Teal\">Valeur</span>"));
  gtk_widget_show (label156);
  gtk_box_pack_start (GTK_BOX (hbox19), label156, FALSE, FALSE, 30);
  gtk_label_set_use_markup (GTK_LABEL (label156), TRUE);

  image25 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox19), image25, FALSE, FALSE, 0);

  labeldef = gtk_label_new (_("  <span color=\"red\">...</span>"));
  gtk_widget_show (labeldef);
  gtk_fixed_put (GTK_FIXED (fixed4), labeldef, 128, 472);
  gtk_widget_set_size_request (labeldef, 168, 40);
  gtk_label_set_use_markup (GTK_LABEL (labeldef), TRUE);

  g_signal_connect ((gpointer) gestion_capteur, "show",
                    G_CALLBACK (on_gestion_capteur_show),
                    NULL);
  g_signal_connect ((gpointer) refrech, "clicked",
                    G_CALLBACK (on_refrech_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierg, "clicked",
                    G_CALLBACK (on_modifierg_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimerg, "clicked",
                    G_CALLBACK (on_supprimerg_clicked),
                    NULL);
  g_signal_connect ((gpointer) alarmants, "clicked",
                    G_CALLBACK (on_alarmants_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourg, "clicked",
                    G_CALLBACK (on_retourg_clicked),
                    NULL);
  g_signal_connect ((gpointer) butt_cherch_gest, "clicked",
                    G_CALLBACK (on_butt_cherch_gest_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher_diff, "clicked",
                    G_CALLBACK (on_chercher_diff_clicked),
                    NULL);
  g_signal_connect ((gpointer) def_marque, "clicked",
                    G_CALLBACK (on_def_marque_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ajout_val, "clicked",
                    G_CALLBACK (on_ajout_val_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label131), refrech);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_capteur, gestion_capteur, "gestion_capteur");
  GLADE_HOOKUP_OBJECT (gestion_capteur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_capteur, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (gestion_capteur, combobox9, "combobox9");
  GLADE_HOOKUP_OBJECT (gestion_capteur, refrech, "refrech");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image24, "image24");
  GLADE_HOOKUP_OBJECT (gestion_capteur, modifierg, "modifierg");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label47, "label47");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_capteur, supprimerg, "supprimerg");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label48, "label48");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alarmants, "alarmants");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label132, "label132");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image26, "image26");
  GLADE_HOOKUP_OBJECT (gestion_capteur, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label146, "label146");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image32, "image32");
  GLADE_HOOKUP_OBJECT (gestion_capteur, retourg, "retourg");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label49, "label49");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_capteur, butt_cherch_gest, "butt_cherch_gest");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image15, "image15");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label109, "label109");
  GLADE_HOOKUP_OBJECT (gestion_capteur, chercher_diff, "chercher_diff");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image27, "image27");
  GLADE_HOOKUP_OBJECT (gestion_capteur, def_marque, "def_marque");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label154, "label154");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image45, "image45");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label131, "label131");
  GLADE_HOOKUP_OBJECT (gestion_capteur, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_capteur, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (gestion_capteur, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (gestion_capteur, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_capteur, ajout_val, "ajout_val");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label156, "label156");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image25, "image25");
  GLADE_HOOKUP_OBJECT (gestion_capteur, labeldef, "labeldef");

  return gestion_capteur;
}

GtkWidget*
create_ajouter_capteur (void)
{
  GtkWidget *ajouter_capteur;
  GtkWidget *fixed23;
  GtkWidget *entry_identf;
  GtkWidget *entry_valeur;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *entry5;
  GtkWidget *label_etat;
  GtkWidget *label145;
  GtkWidget *image38;
  GtkWidget *ident_ajout;
  GtkWidget *valider;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *label56;
  GtkWidget *image8;
  GtkWidget *retoura;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *label57;
  GtkWidget *image9;
  GtkWidget *label112;
  GtkWidget *label136;
  GtkWidget *label141;
  GtkWidget *combobox10;
  GtkWidget *type_ajout;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *date_mise_ajout;
  GtkWidget *etat_capt_ajou;
  GtkWidget *combobox7;

  ajouter_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_capteur), _("Ajouter un capteur"));
  gtk_window_set_position (GTK_WINDOW (ajouter_capteur), GTK_WIN_POS_CENTER);

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (ajouter_capteur), fixed23);

  entry_identf = gtk_entry_new ();
  gtk_widget_show (entry_identf);
  gtk_fixed_put (GTK_FIXED (fixed23), entry_identf, 648, 48);
  gtk_widget_set_size_request (entry_identf, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_identf), 8226);

  entry_valeur = gtk_entry_new ();
  gtk_widget_show (entry_valeur);
  gtk_fixed_put (GTK_FIXED (fixed23), entry_valeur, 136, 112);
  gtk_widget_set_size_request (entry_valeur, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valeur), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed23), spinbutton1, 616, 160);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed23), spinbutton2, 680, 160);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (2017, 2017, 2021, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed23), spinbutton3, 744, 160);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed23), entry5, 136, 160);
  gtk_widget_set_size_request (entry5, 152, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label_etat = gtk_label_new (_("<span color =\"orangered\"></span>"));
  gtk_widget_show (label_etat);
  gtk_fixed_put (GTK_FIXED (fixed23), label_etat, 376, 128);
  gtk_widget_set_size_request (label_etat, 160, 32);
  gtk_label_set_use_markup (GTK_LABEL (label_etat), TRUE);

  label145 = gtk_label_new (_("<span color =\"orangered\"></span>"));
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (fixed23), label145, 384, 392);
  gtk_widget_set_size_request (label145, 152, 32);
  gtk_label_set_use_markup (GTK_LABEL (label145), TRUE);

  image38 = create_pixmap (ajouter_capteur, "farm-background-2560x1600-htc-WTG3047373-1024x640.jpeg");
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed23), image38, 0, 0);
  gtk_widget_set_size_request (image38, 1024, 640);

  ident_ajout = gtk_label_new (_("<span color =\"white\">Identifiant</span>"));
  gtk_widget_show (ident_ajout);
  gtk_fixed_put (GTK_FIXED (fixed23), ident_ajout, 496, 48);
  gtk_widget_set_size_request (ident_ajout, 120, 30);
  gtk_label_set_use_markup (GTK_LABEL (ident_ajout), TRUE);

  valider = gtk_button_new ();
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed23), valider, 344, 440);
  gtk_widget_set_size_request (valider, 95, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (valider), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  label56 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox8), label56, FALSE, FALSE, 6);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  retoura = gtk_button_new ();
  gtk_widget_show (retoura);
  gtk_fixed_put (GTK_FIXED (fixed23), retoura, 456, 440);
  gtk_widget_set_size_request (retoura, 95, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (retoura), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  label57 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox9), label57, FALSE, FALSE, 6);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label112 = gtk_label_new (_("<span color =\"darkblue\">Valeur Max</span>"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed23), label112, 8, 112);
  gtk_widget_set_size_request (label112, 120, 30);
  gtk_label_set_use_markup (GTK_LABEL (label112), TRUE);

  label136 = gtk_label_new (_("<span color =\"darkblue\">Valeur Min</span>"));
  gtk_widget_show (label136);
  gtk_fixed_put (GTK_FIXED (fixed23), label136, 8, 160);
  gtk_widget_set_size_request (label136, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label136), TRUE);

  label141 = gtk_label_new (_("<span color =\"darkblue\">Marque</span>"));
  gtk_widget_show (label141);
  gtk_fixed_put (GTK_FIXED (fixed23), label141, 8, 56);
  gtk_widget_set_size_request (label141, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (label141), TRUE);

  combobox10 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox10);
  gtk_fixed_put (GTK_FIXED (fixed23), combobox10, 136, 56);
  gtk_widget_set_size_request (combobox10, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("FarmTRX"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("MC_Sieve_Sensor"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("TOPCON"));

  type_ajout = gtk_label_new (_("<span color =\"darkblue\">Type</span>"));
  gtk_widget_show (type_ajout);
  gtk_fixed_put (GTK_FIXED (fixed23), type_ajout, 8, 224);
  gtk_widget_set_size_request (type_ajout, 120, 30);
  gtk_label_set_use_markup (GTK_LABEL (type_ajout), TRUE);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed23), radiobutton1, 128, 232);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_button_set_focus_on_click (GTK_BUTTON (radiobutton1), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Humidit\303\251"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed23), radiobutton2, 264, 232);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  date_mise_ajout = gtk_label_new (_("<span color =\"white\">Date</span> "));
  gtk_widget_show (date_mise_ajout);
  gtk_fixed_put (GTK_FIXED (fixed23), date_mise_ajout, 480, 160);
  gtk_widget_set_size_request (date_mise_ajout, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (date_mise_ajout), TRUE);

  etat_capt_ajou = gtk_label_new (_("<span color =\"white\">Etat</span>"));
  gtk_widget_show (etat_capt_ajou);
  gtk_fixed_put (GTK_FIXED (fixed23), etat_capt_ajou, 488, 104);
  gtk_widget_set_size_request (etat_capt_ajou, 120, 30);
  gtk_label_set_use_markup (GTK_LABEL (etat_capt_ajou), TRUE);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed23), combobox7, 648, 104);
  gtk_widget_set_size_request (combobox7, 150, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("PANNE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("OK"));

  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) retoura, "clicked",
                    G_CALLBACK (on_retoura_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_capteur, ajouter_capteur, "ajouter_capteur");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, entry_identf, "entry_identf");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, entry_valeur, "entry_valeur");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label_etat, "label_etat");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label145, "label145");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, image38, "image38");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, ident_ajout, "ident_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, valider, "valider");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label56, "label56");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, retoura, "retoura");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label57, "label57");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, image9, "image9");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label112, "label112");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label136, "label136");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label141, "label141");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, combobox10, "combobox10");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, type_ajout, "type_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, date_mise_ajout, "date_mise_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, etat_capt_ajou, "etat_capt_ajou");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, combobox7, "combobox7");

  return ajouter_capteur;
}

GtkWidget*
create_supprimer_capteur (void)
{
  GtkWidget *supprimer_capteur;
  GtkWidget *fixed25;
  GtkWidget *image39;
  GtkWidget *annuler_supprimer;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *anuler_supp;
  GtkWidget *image12;
  GtkWidget *ok_supprimer;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *label118;
  GtkWidget *image16;
  GtkWidget *label_supp_non;
  GtkWidget *label125;

  supprimer_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_capteur), _("Supprimer"));
  gtk_window_set_position (GTK_WINDOW (supprimer_capteur), GTK_WIN_POS_CENTER);

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (supprimer_capteur), fixed25);

  image39 = create_pixmap (supprimer_capteur, "farm-background-2560x1600-htc-WTG3047373-1024x640.jpeg");
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed25), image39, 0, 0);
  gtk_widget_set_size_request (image39, 1024, 640);

  annuler_supprimer = gtk_button_new ();
  gtk_widget_show (annuler_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed25), annuler_supprimer, 536, 496);
  gtk_widget_set_size_request (annuler_supprimer, 105, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (annuler_supprimer), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  anuler_supp = gtk_label_new_with_mnemonic (_("<span color =\"teal\">retour</span>"));
  gtk_widget_show (anuler_supp);
  gtk_box_pack_start (GTK_BOX (hbox12), anuler_supp, FALSE, FALSE, 9);
  gtk_label_set_use_markup (GTK_LABEL (anuler_supp), TRUE);

  image12 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  ok_supprimer = gtk_button_new ();
  gtk_widget_show (ok_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed25), ok_supprimer, 416, 496);
  gtk_widget_set_size_request (ok_supprimer, 105, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (ok_supprimer), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  label118 = gtk_label_new_with_mnemonic (_("<span color =\"teal\">Oui</span>"));
  gtk_widget_show (label118);
  gtk_box_pack_start (GTK_BOX (hbox16), label118, FALSE, FALSE, 13);
  gtk_label_set_use_markup (GTK_LABEL (label118), TRUE);

  image16 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label_supp_non = gtk_label_new (_("<span color=\"white\"></span>"));
  gtk_widget_show (label_supp_non);
  gtk_fixed_put (GTK_FIXED (fixed25), label_supp_non, 280, 272);
  gtk_widget_set_size_request (label_supp_non, 136, 48);
  gtk_label_set_use_markup (GTK_LABEL (label_supp_non), TRUE);

  label125 = gtk_label_new (_("<span color =\"darkred\">Voulez-vous supprimer ce capteur ?</span>"));
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed25), label125, 384, 280);
  gtk_widget_set_size_request (label125, 336, 40);
  gtk_label_set_use_markup (GTK_LABEL (label125), TRUE);

  g_signal_connect ((gpointer) supprimer_capteur, "show",
                    G_CALLBACK (on_supprimer_capteur_show),
                    NULL);
  g_signal_connect ((gpointer) annuler_supprimer, "clicked",
                    G_CALLBACK (on_annuler_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) ok_supprimer, "clicked",
                    G_CALLBACK (on_ok_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_capteur, supprimer_capteur, "supprimer_capteur");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, image39, "image39");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, annuler_supprimer, "annuler_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, anuler_supp, "anuler_supp");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, ok_supprimer, "ok_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, label118, "label118");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, image16, "image16");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, label_supp_non, "label_supp_non");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, label125, "label125");

  return supprimer_capteur;
}

GtkWidget*
create_modifier_capteur (void)
{
  GtkWidget *modifier_capteur;
  GtkWidget *fixed28;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *entry6;
  GtkWidget *image40;
  GtkWidget *label113;
  GtkWidget *label142;
  GtkWidget *label114;
  GtkWidget *label137;
  GtkWidget *label123;
  GtkWidget *ok_modifier;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *label120;
  GtkWidget *image17;
  GtkWidget *retour_modifier;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *label121;
  GtkWidget *image18;
  GtkWidget *combobox11;
  GtkWidget *label116;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton3;
  GtkWidget *label151;
  GtkWidget *combobox8;
  GtkWidget *label117;

  modifier_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_capteur), _("Modifier"));
  gtk_window_set_position (GTK_WINDOW (modifier_capteur), GTK_WIN_POS_CENTER);

  fixed28 = gtk_fixed_new ();
  gtk_widget_show (fixed28);
  gtk_container_add (GTK_CONTAINER (modifier_capteur), fixed28);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed28), entry1, 712, 24);
  gtk_widget_set_size_request (entry1, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed28), entry2, 168, 80);
  gtk_widget_set_size_request (entry2, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 30, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed28), spinbutton4, 704, 160);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed28), spinbutton5, 776, 160);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (2017, 2017, 2021, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed28), spinbutton6, 848, 160);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed28), entry6, 168, 136);
  gtk_widget_set_size_request (entry6, 152, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  image40 = create_pixmap (modifier_capteur, "farm-background-2560x1600-htc-WTG3047373-1024x640.jpeg");
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed28), image40, 0, 0);
  gtk_widget_set_size_request (image40, 1024, 640);

  label113 = gtk_label_new (_("<span color =\"white\">Identifiant</span>"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed28), label113, 592, 24);
  gtk_widget_set_size_request (label113, 120, 30);
  gtk_label_set_use_markup (GTK_LABEL (label113), TRUE);

  label142 = gtk_label_new (_("<span color =\"darkblue\">Emplacement</span>"));
  gtk_widget_show (label142);
  gtk_fixed_put (GTK_FIXED (fixed28), label142, 32, 24);
  gtk_widget_set_size_request (label142, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label142), TRUE);

  label114 = gtk_label_new (_("<span color =\"darkblue\">Valeur Max</span>"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed28), label114, 40, 80);
  gtk_widget_set_size_request (label114, 120, 30);
  gtk_label_set_use_markup (GTK_LABEL (label114), TRUE);

  label137 = gtk_label_new (_("<span color =\"darkblue\">Valeur Min</span>"));
  gtk_widget_show (label137);
  gtk_fixed_put (GTK_FIXED (fixed28), label137, 40, 136);
  gtk_widget_set_size_request (label137, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label137), TRUE);

  label123 = gtk_label_new (_("....."));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed28), label123, 392, 280);
  gtk_widget_set_size_request (label123, 152, 48);

  ok_modifier = gtk_button_new ();
  gtk_widget_show (ok_modifier);
  gtk_fixed_put (GTK_FIXED (fixed28), ok_modifier, 400, 504);
  gtk_widget_set_size_request (ok_modifier, 95, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (ok_modifier), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  label120 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label120);
  gtk_box_pack_start (GTK_BOX (hbox17), label120, FALSE, FALSE, 15);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  retour_modifier = gtk_button_new ();
  gtk_widget_show (retour_modifier);
  gtk_fixed_put (GTK_FIXED (fixed28), retour_modifier, 512, 504);
  gtk_widget_set_size_request (retour_modifier, 96, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (retour_modifier), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  label121 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label121);
  gtk_box_pack_start (GTK_BOX (hbox18), label121, FALSE, FALSE, 7);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  combobox11 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox11);
  gtk_fixed_put (GTK_FIXED (fixed28), combobox11, 168, 24);
  gtk_widget_set_size_request (combobox11, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox11), _("FarmTRX"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox11), _("MC_Sieve_Sensor"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox11), _("TOPCON"));

  label116 = gtk_label_new (_("<span color =\"darkblue\">Type</span>"));
  gtk_widget_show (label116);
  gtk_fixed_put (GTK_FIXED (fixed28), label116, 40, 208);
  gtk_widget_set_size_request (label116, 120, 30);
  gtk_label_set_use_markup (GTK_LABEL (label116), TRUE);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Humidite"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed28), radiobutton4, 288, 208);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed28), radiobutton3, 152, 208);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label151 = gtk_label_new (_("<span color =\"white\">Etat</span>"));
  gtk_widget_show (label151);
  gtk_fixed_put (GTK_FIXED (fixed28), label151, 576, 88);
  gtk_widget_set_size_request (label151, 120, 30);
  gtk_label_set_use_markup (GTK_LABEL (label151), TRUE);

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed28), combobox8, 712, 96);
  gtk_widget_set_size_request (combobox8, 150, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("PANNE\t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("OK"));

  label117 = gtk_label_new (_("<span color =\"white\">Date</span> "));
  gtk_widget_show (label117);
  gtk_fixed_put (GTK_FIXED (fixed28), label117, 568, 152);
  gtk_widget_set_size_request (label117, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (label117), TRUE);

  g_signal_connect ((gpointer) modifier_capteur, "show",
                    G_CALLBACK (on_modifier_capteur_show),
                    NULL);
  g_signal_connect ((gpointer) ok_modifier, "clicked",
                    G_CALLBACK (on_ok_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_modifier, "clicked",
                    G_CALLBACK (on_retour_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_capteur, modifier_capteur, "modifier_capteur");
  GLADE_HOOKUP_OBJECT (modifier_capteur, fixed28, "fixed28");
  GLADE_HOOKUP_OBJECT (modifier_capteur, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (modifier_capteur, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (modifier_capteur, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (modifier_capteur, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (modifier_capteur, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (modifier_capteur, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (modifier_capteur, image40, "image40");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label113, "label113");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label142, "label142");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label114, "label114");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label137, "label137");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label123, "label123");
  GLADE_HOOKUP_OBJECT (modifier_capteur, ok_modifier, "ok_modifier");
  GLADE_HOOKUP_OBJECT (modifier_capteur, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (modifier_capteur, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label120, "label120");
  GLADE_HOOKUP_OBJECT (modifier_capteur, image17, "image17");
  GLADE_HOOKUP_OBJECT (modifier_capteur, retour_modifier, "retour_modifier");
  GLADE_HOOKUP_OBJECT (modifier_capteur, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (modifier_capteur, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label121, "label121");
  GLADE_HOOKUP_OBJECT (modifier_capteur, image18, "image18");
  GLADE_HOOKUP_OBJECT (modifier_capteur, combobox11, "combobox11");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label116, "label116");
  GLADE_HOOKUP_OBJECT (modifier_capteur, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (modifier_capteur, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label151, "label151");
  GLADE_HOOKUP_OBJECT (modifier_capteur, combobox8, "combobox8");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label117, "label117");

  return modifier_capteur;
}

GtkWidget*
create_ajout_valeur (void)
{
  GtkWidget *ajout_valeur;
  GtkWidget *fixed29;
  GtkWidget *entry_valeur_ajout_valeur;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *entry7;
  GtkWidget *image41;
  GtkWidget *label134;
  GtkWidget *label138;
  GtkWidget *label135;
  GtkWidget *ok_ajout_valeur;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *label139;
  GtkWidget *image28;
  GtkWidget *retour_ajout_valeur;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *label140;
  GtkWidget *image29;

  ajout_valeur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_valeur), _("Modifier V max/min"));
  gtk_window_set_position (GTK_WINDOW (ajout_valeur), GTK_WIN_POS_CENTER);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_container_add (GTK_CONTAINER (ajout_valeur), fixed29);

  entry_valeur_ajout_valeur = gtk_entry_new ();
  gtk_widget_show (entry_valeur_ajout_valeur);
  gtk_fixed_put (GTK_FIXED (fixed29), entry_valeur_ajout_valeur, 568, 16);
  gtk_widget_set_size_request (entry_valeur_ajout_valeur, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valeur_ajout_valeur), 8226);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 30, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed29), spinbutton7, 560, 152);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  spinbutton8_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed29), spinbutton8, 624, 152);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  spinbutton9_adj = gtk_adjustment_new (2010, 2010, 2050, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed29), spinbutton9, 688, 152);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed29), entry7, 568, 72);
  gtk_widget_set_size_request (entry7, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  image41 = create_pixmap (ajout_valeur, "farm-background-2560x1600-htc-WTG3047373-1024x640.jpeg");
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (fixed29), image41, 0, 0);
  gtk_widget_set_size_request (image41, 1024, 640);

  label134 = gtk_label_new (_("<span color =\"white\">Valeur Max</span>"));
  gtk_widget_show (label134);
  gtk_fixed_put (GTK_FIXED (fixed29), label134, 368, 16);
  gtk_widget_set_size_request (label134, 152, 32);
  gtk_label_set_use_markup (GTK_LABEL (label134), TRUE);

  label138 = gtk_label_new (_("<span color =\"white\">Valeur Min</span>"));
  gtk_widget_show (label138);
  gtk_fixed_put (GTK_FIXED (fixed29), label138, 368, 80);
  gtk_widget_set_size_request (label138, 152, 32);
  gtk_label_set_use_markup (GTK_LABEL (label138), TRUE);

  label135 = gtk_label_new (_("<span color =\"white\">Date</span> "));
  gtk_widget_show (label135);
  gtk_fixed_put (GTK_FIXED (fixed29), label135, 408, 144);
  gtk_widget_set_size_request (label135, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label135), TRUE);

  ok_ajout_valeur = gtk_button_new ();
  gtk_widget_show (ok_ajout_valeur);
  gtk_fixed_put (GTK_FIXED (fixed29), ok_ajout_valeur, 720, 416);
  gtk_widget_set_size_request (ok_ajout_valeur, 95, 40);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (ok_ajout_valeur), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  label139 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label139);
  gtk_box_pack_start (GTK_BOX (hbox21), label139, FALSE, FALSE, 12);

  image28 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox21), image28, FALSE, FALSE, 0);

  retour_ajout_valeur = gtk_button_new ();
  gtk_widget_show (retour_ajout_valeur);
  gtk_fixed_put (GTK_FIXED (fixed29), retour_ajout_valeur, 592, 416);
  gtk_widget_set_size_request (retour_ajout_valeur, 104, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (retour_ajout_valeur), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  label140 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label140);
  gtk_box_pack_start (GTK_BOX (hbox22), label140, FALSE, FALSE, 7);

  image29 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox22), image29, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ajout_valeur, "show",
                    G_CALLBACK (on_ajout_valeur_show),
                    NULL);
  g_signal_connect ((gpointer) ok_ajout_valeur, "clicked",
                    G_CALLBACK (on_ok_ajout_valeur_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_ajout_valeur, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_valeur, ajout_valeur, "ajout_valeur");
  GLADE_HOOKUP_OBJECT (ajout_valeur, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (ajout_valeur, entry_valeur_ajout_valeur, "entry_valeur_ajout_valeur");
  GLADE_HOOKUP_OBJECT (ajout_valeur, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (ajout_valeur, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (ajout_valeur, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (ajout_valeur, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (ajout_valeur, image41, "image41");
  GLADE_HOOKUP_OBJECT (ajout_valeur, label134, "label134");
  GLADE_HOOKUP_OBJECT (ajout_valeur, label138, "label138");
  GLADE_HOOKUP_OBJECT (ajout_valeur, label135, "label135");
  GLADE_HOOKUP_OBJECT (ajout_valeur, ok_ajout_valeur, "ok_ajout_valeur");
  GLADE_HOOKUP_OBJECT (ajout_valeur, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (ajout_valeur, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (ajout_valeur, label139, "label139");
  GLADE_HOOKUP_OBJECT (ajout_valeur, image28, "image28");
  GLADE_HOOKUP_OBJECT (ajout_valeur, retour_ajout_valeur, "retour_ajout_valeur");
  GLADE_HOOKUP_OBJECT (ajout_valeur, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (ajout_valeur, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (ajout_valeur, label140, "label140");
  GLADE_HOOKUP_OBJECT (ajout_valeur, image29, "image29");

  return ajout_valeur;
}

GtkWidget*
create_Alarmants (void)
{
  GtkWidget *Alarmants;
  GtkWidget *fixed30;
  GtkObject *ja_adj;
  GtkWidget *ja;
  GtkObject *ma_adj;
  GtkWidget *ma;
  GtkObject *aa_adj;
  GtkWidget *aa;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkWidget *image42;
  GtkWidget *actualiser;
  GtkWidget *image35;
  GtkWidget *label147;
  GtkWidget *label148;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport2;
  GtkWidget *fixed31;
  GtkWidget *treeview2;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport3;
  GtkWidget *fixed32;
  GtkWidget *treeview3;
  GtkWidget *cherHum;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *label149;
  GtkWidget *image33;
  GtkWidget *cheralarm;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *label144;
  GtkWidget *image31;
  GtkWidget *plusalarm;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *label150;
  GtkWidget *image34;
  GtkWidget *retour_alarmant;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image30;
  GtkWidget *label143;

  Alarmants = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Alarmants), _("Valeurs des Capteurs "));
  gtk_window_set_position (GTK_WINDOW (Alarmants), GTK_WIN_POS_CENTER);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_container_add (GTK_CONTAINER (Alarmants), fixed30);

  ja_adj = gtk_adjustment_new (1, 1, 30, 1, 10, 10);
  ja = gtk_spin_button_new (GTK_ADJUSTMENT (ja_adj), 1, 0);
  gtk_widget_show (ja);
  gtk_fixed_put (GTK_FIXED (fixed30), ja, 264, 568);
  gtk_widget_set_size_request (ja, 48, 24);

  ma_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ma = gtk_spin_button_new (GTK_ADJUSTMENT (ma_adj), 1, 0);
  gtk_widget_show (ma);
  gtk_fixed_put (GTK_FIXED (fixed30), ma, 320, 568);
  gtk_widget_set_size_request (ma, 48, 24);

  aa_adj = gtk_adjustment_new (2017, 2017, 2021, 1, 10, 10);
  aa = gtk_spin_button_new (GTK_ADJUSTMENT (aa_adj), 1, 0);
  gtk_widget_show (aa);
  gtk_fixed_put (GTK_FIXED (fixed30), aa, 376, 568);
  gtk_widget_set_size_request (aa, 64, 24);

  spinbutton10_adj = gtk_adjustment_new (1, 1, 30, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton10, 752, 568);
  gtk_widget_set_size_request (spinbutton10, 48, 24);

  spinbutton11_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton11, 808, 568);
  gtk_widget_set_size_request (spinbutton11, 48, 24);

  spinbutton12_adj = gtk_adjustment_new (2017, 2017, 2021, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton12, 864, 568);
  gtk_widget_set_size_request (spinbutton12, 64, 24);

  image42 = create_pixmap (Alarmants, "farm-background-2560x1600-htc-WTG3047373-1024x640.jpeg");
  gtk_widget_show (image42);
  gtk_fixed_put (GTK_FIXED (fixed30), image42, 0, 0);
  gtk_widget_set_size_request (image42, 1024, 640);

  actualiser = gtk_button_new ();
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed30), actualiser, 0, 0);
  gtk_widget_set_size_request (actualiser, 30, 30);

  image35 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_container_add (GTK_CONTAINER (actualiser), image35);

  label147 = gtk_label_new (_("<span color =\"white\">Temp\303\251rature</span>"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed30), label147, 216, 0);
  gtk_widget_set_size_request (label147, 250, 40);
  gtk_label_set_use_markup (GTK_LABEL (label147), TRUE);

  label148 = gtk_label_new (_("<span color =\"white\">Humidit\303\251</span>"));
  gtk_widget_show (label148);
  gtk_fixed_put (GTK_FIXED (fixed30), label148, 704, 0);
  gtk_widget_set_size_request (label148, 250, 40);
  gtk_label_set_use_markup (GTK_LABEL (label148), TRUE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed30), scrolledwindow2, 192, 48);
  gtk_widget_set_size_request (scrolledwindow2, 350, 500);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport2);

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_container_add (GTK_CONTAINER (viewport2), fixed31);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed31), treeview2, 0, 0);
  gtk_widget_set_size_request (treeview2, 335, 10000);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview2), TRUE);
  gtk_tree_view_set_hover_selection (GTK_TREE_VIEW (treeview2), TRUE);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed30), scrolledwindow3, 664, 48);
  gtk_widget_set_size_request (scrolledwindow3, 340, 500);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport3);

  fixed32 = gtk_fixed_new ();
  gtk_widget_show (fixed32);
  gtk_container_add (GTK_CONTAINER (viewport3), fixed32);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed32), treeview3, 0, 0);
  gtk_widget_set_size_request (treeview3, 335, 10000);
  gtk_container_set_border_width (GTK_CONTAINER (treeview3), 7);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview3), TRUE);
  gtk_tree_view_set_hover_selection (GTK_TREE_VIEW (treeview3), TRUE);

  cherHum = gtk_button_new ();
  gtk_widget_show (cherHum);
  gtk_fixed_put (GTK_FIXED (fixed30), cherHum, 776, 608);
  gtk_widget_set_size_request (cherHum, 130, 30);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (cherHum), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  label149 = gtk_label_new_with_mnemonic (_("<span color =\"teal\">Alarmantes H</span> "));
  gtk_widget_show (label149);
  gtk_box_pack_start (GTK_BOX (hbox26), label149, FALSE, FALSE, 3);
  gtk_label_set_use_markup (GTK_LABEL (label149), TRUE);

  image33 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox26), image33, FALSE, FALSE, 0);

  cheralarm = gtk_button_new ();
  gtk_widget_show (cheralarm);
  gtk_fixed_put (GTK_FIXED (fixed30), cheralarm, 288, 608);
  gtk_widget_set_size_request (cheralarm, 130, 30);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (cheralarm), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  label144 = gtk_label_new_with_mnemonic (_("<span color =\"teal\">Alarmantes T</span> "));
  gtk_widget_show (label144);
  gtk_box_pack_start (GTK_BOX (hbox24), label144, FALSE, FALSE, 4);
  gtk_label_set_use_markup (GTK_LABEL (label144), TRUE);

  image31 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox24), image31, FALSE, FALSE, 0);

  plusalarm = gtk_button_new ();
  gtk_widget_show (plusalarm);
  gtk_fixed_put (GTK_FIXED (fixed30), plusalarm, 0, 104);
  gtk_widget_set_size_request (plusalarm, 176, 56);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (plusalarm), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  label150 = gtk_label_new_with_mnemonic (_("<span color =\"orangered\">Les plus alarmants</span>"));
  gtk_widget_show (label150);
  gtk_box_pack_start (GTK_BOX (hbox27), label150, FALSE, FALSE, 7);
  gtk_label_set_use_markup (GTK_LABEL (label150), TRUE);

  image34 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox27), image34, FALSE, FALSE, 0);

  retour_alarmant = gtk_button_new ();
  gtk_widget_show (retour_alarmant);
  gtk_fixed_put (GTK_FIXED (fixed30), retour_alarmant, 8, 592);
  gtk_widget_set_size_request (retour_alarmant, 95, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (retour_alarmant), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image30 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox23), image30, FALSE, FALSE, 0);

  label143 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label143);
  gtk_box_pack_start (GTK_BOX (hbox23), label143, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) cherHum, "clicked",
                    G_CALLBACK (on_cherHum_clicked),
                    NULL);
  g_signal_connect ((gpointer) cheralarm, "clicked",
                    G_CALLBACK (on_cheralarm_clicked),
                    NULL);
  g_signal_connect ((gpointer) plusalarm, "clicked",
                    G_CALLBACK (on_plusalarm_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_alarmant, "clicked",
                    G_CALLBACK (on_retour_alarmant_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Alarmants, Alarmants, "Alarmants");
  GLADE_HOOKUP_OBJECT (Alarmants, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (Alarmants, ja, "ja");
  GLADE_HOOKUP_OBJECT (Alarmants, ma, "ma");
  GLADE_HOOKUP_OBJECT (Alarmants, aa, "aa");
  GLADE_HOOKUP_OBJECT (Alarmants, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (Alarmants, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (Alarmants, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (Alarmants, image42, "image42");
  GLADE_HOOKUP_OBJECT (Alarmants, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (Alarmants, image35, "image35");
  GLADE_HOOKUP_OBJECT (Alarmants, label147, "label147");
  GLADE_HOOKUP_OBJECT (Alarmants, label148, "label148");
  GLADE_HOOKUP_OBJECT (Alarmants, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (Alarmants, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (Alarmants, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (Alarmants, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (Alarmants, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (Alarmants, viewport3, "viewport3");
  GLADE_HOOKUP_OBJECT (Alarmants, fixed32, "fixed32");
  GLADE_HOOKUP_OBJECT (Alarmants, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (Alarmants, cherHum, "cherHum");
  GLADE_HOOKUP_OBJECT (Alarmants, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (Alarmants, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (Alarmants, label149, "label149");
  GLADE_HOOKUP_OBJECT (Alarmants, image33, "image33");
  GLADE_HOOKUP_OBJECT (Alarmants, cheralarm, "cheralarm");
  GLADE_HOOKUP_OBJECT (Alarmants, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (Alarmants, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (Alarmants, label144, "label144");
  GLADE_HOOKUP_OBJECT (Alarmants, image31, "image31");
  GLADE_HOOKUP_OBJECT (Alarmants, plusalarm, "plusalarm");
  GLADE_HOOKUP_OBJECT (Alarmants, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (Alarmants, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (Alarmants, label150, "label150");
  GLADE_HOOKUP_OBJECT (Alarmants, image34, "image34");
  GLADE_HOOKUP_OBJECT (Alarmants, retour_alarmant, "retour_alarmant");
  GLADE_HOOKUP_OBJECT (Alarmants, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Alarmants, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (Alarmants, image30, "image30");
  GLADE_HOOKUP_OBJECT (Alarmants, label143, "label143");

  return Alarmants;
}

