/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_inscription (void);
GtkWidget* create_authentification (void);
GtkWidget* create_gestion_capteur (void);
GtkWidget* create_ajouter_capteur (void);
GtkWidget* create_supprimer_capteur (void);
GtkWidget* create_modifier_capteur (void);
GtkWidget* create_ajout_valeur (void);
GtkWidget* create_Alarmants (void);
